Automatically publish Docker-containers

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,7 +1,11 @@
 name: Docker
 
-"on": workflow_dispatch
-
+"on":
+  push:
+    branches: [main, develop]
+  pull_request:
+  release:
+    types: [published]
 jobs:
   build_push:
     name: Build and push Docker image
@@ -12,14 +16,45 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+      # On release, the version embedded in the shell-script should match the
+      # release-tag; in all other cases, only pass along pre-release versions
+      # (e.g. "1.3.0-dev") – as signified by a hyphen in the version string...
       - name: Retrieve sysmon-mqtt version
+        env:
+          RELEASE_VERSION: >-
+            ${{ github.event_name == 'release' && github.ref_name || '#NA' }}
         id: sysmon
         run: |
           semver=$(
             ./sysmon.sh --version | \
             grep -oE '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-[-a-z0-9\.]+)?'
           )
-          echo semver="v$semver" >> "$GITHUB_OUTPUT"
+          if [ "$RELEASE_VERSION" == "#NA" ]; then
+            if [[ $semver =~ .+-.+ ]]; then
+              echo semver="v$semver" >> "$GITHUB_OUTPUT"
+            fi
+          else
+            if [ "$RELEASE_VERSION" != "v$semver" ]; then
+              printf "::warning::"
+              printf "Invalid sysmon-mqtt version 'v$semver' "
+              printf "(expected '$RELEASE_VERSION') – "
+              printf "aborting...\n"
+              exit 1
+            fi
+            echo semver="v$semver" >> "$GITHUB_OUTPUT"
+          fi
+      # The following tags are generated:
+      #  * on release – "multi-stage" semantic version, "latest" and SHA
+      #  * push to main-branch – SHA
+      #  * push to develop-branch – "edge" and SHA
+      #  * push to pull-request – "pr-123" (ie, the PR number)
+      # By convention, releases are drafted from the main-branch. The SHA-based
+      # tagging there is thus primarily a final smoke-test. Once a release is
+      # published, the result of its "Build and push"-workflow is tagged with
+      # the same SHA...
+      # If a pre-release semantic version (e.g. "1.3.0-dev") is set in the
+      # shell-script itself, the container is also tagged with that _exact_
+      # version string (_not_ including the "multi-stage" semantic version).
       - name: Generate Docker metadata
         id: meta
         uses: docker/metadata-action@v4
@@ -29,13 +64,13 @@ jobs:
             ghcr.io/thijsputman/sysmon-mqtt
           # yamllint disable rule:line-length
           tags: |
-            type=sha
             type=semver,pattern={{version}},value=${{ steps.sysmon.outputs.semver }}
             type=semver,pattern={{major}}.{{minor}},value=${{ steps.sysmon.outputs.semver }}
             type=semver,pattern={{major}},value=${{ steps.sysmon.outputs.semver }}
-            type=ref,event=pr,prefix=pr-
+            type=ref,event=pr
             type=edge,branch=develop
-            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
+            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
+            type=sha,enable=${{ contains(fromJSON('["main", "develop"]'), github.ref_name) || github.event_name == 'release' }}
           # yamllint enable rule:line-length
           flavor: |
             latest=false
