Remove Docker-support (#13)
Unused, and unmaintained for quite some time.

Also, hindsight being 20/20: Running a hardware monitoring script inside
in a Docker-container makes little sense...

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,4 @@
 name: Release
-
 "on":
   release:
     types: [published]
@@ -8,24 +7,15 @@ jobs:
     uses: ./.github/workflows/linter.yml
     permissions:
       contents: read
-  build_push:
-    uses: ./.github/workflows/docker.yml
-    with:
-      release: true
-    secrets: inherit
-    permissions:
-      contents: read
-      packages: write
-    needs: lint
   release:
     name: Publish release
     runs-on: ubuntu-22.04
     permissions:
       contents: write
-    needs: build_push
+    needs: [lint]
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v7
       - name: Install GitHub CLI
         # "env.ACT" is added by nektos/act locally – using from-/toJSON prevents
         # the GitHub Actions VS Code extension from complaining about a
@@ -33,18 +23,35 @@ jobs:
         if: ${{ fromJSON(toJSON(env)).ACT }}
         run: |
           mkdir -p "$HOME/.local/bin"
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
-          gh_cli_file=gh_${GH_CLI_VERSION}_linux_amd64.tar.gz
-          wget $GH_CLI_URL/v$GH_CLI_VERSION/$gh_cli_file
-          tar -xzf $gh_cli_file
-          mv gh_${GH_CLI_VERSION}_linux_amd64/bin/gh ~/.local/bin
+          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
+          gh_cli_file="gh_${GH_CLI_VERSION}_linux_amd64.tar.gz"
+          wget "$GH_CLI_URL/v$GH_CLI_VERSION/$gh_cli_file"
+          tar -xzf "$gh_cli_file"
+          mv "gh_${GH_CLI_VERSION}_linux_amd64/bin/gh" ~/.local/bin
         env:
           GH_CLI_VERSION: 2.42.1
           GH_CLI_URL: https://github.com/cli/cli/releases/download
-      - name: Attach "sysmon.sh" to release
-        if: ${{github.event.release.tag_name}}
+      # The version embedded in the shell-script should match the release-tag
+      - name: Retrieve sysmon-mqtt version
+        env:
+          RELEASE_VERSION: >-
+            ${{ github.event.release.tag_name }}
         run: |
-          gh release upload ${{github.event.release.tag_name}} \
+          semver=$(
+            ./sysmon.sh --version | \
+            grep -oE '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-[-a-z0-9\.]+)?'
+          )
+          if [[ $RELEASE_VERSION != "v$semver" ]]; then
+            printf "::warning::"
+            printf "Invalid sysmon-mqtt version 'v%s' " "$semver"
+            printf "(expected '%s') – " "$RELEASE_VERSION"
+            printf "aborting...\n"
+            exit 1
+          fi
+      - name: Attach "sysmon.sh" to release
+        if: ${{ github.event.release.tag_name }}
+        run: |
+          gh release upload ${{ github.event.release.tag_name }} \
             ./sysmon.sh --clobber
         env:
           GITHUB_TOKEN: ${{ github.TOKEN }}
